### ISSUE TITLE
Update CLI project URL

### ISSUE THREAD

**Issue by zyndagj** [TACC-Cloud/agave-docs#27]
The URL in [command-line-interface.rst](https://github.com/TACC-Cloud/agave-docs/blob/26649a99f868d0e5e2b7f2d86935b88445d000a2/docs/agave/tooling/command-line-interface.rst) should probably point to either

- https://github.com/TACC-Cloud/tapis-cli-ng
- https://github.com/TACC-Cloud/agave-cli

instead of https://github.com/TACC/agavepy which is more of a python library instead of a CLI.

**Comment by BranRitz** [comment]
Url has been updated
